# Generated by Django 4.1.4 on 2022-12-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('school_domain', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('student_domain', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('time_zone', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('terms', models.IntegerField()),
                ('logo', models.CharField(blank=True, max_length=100, null=True)),
                ('enable_drop', models.IntegerField()),
                ('pickup_range', models.FloatField(blank=True, null=True)),
                ('picup_endtime', models.TimeField(blank=True, db_column='picup_endTime', null=True)),
                ('picup_starttime', models.TimeField(blank=True, db_column='picup_startTime', null=True)),
                ('visible', models.IntegerField()),
            ],
            options={
                'db_table': 'school',
                'managed': False,
            },
        ),
    ]
