# Generated by Django 4.1.4 on 2022-12-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolChildren',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True, unique=True)),
                ('parent_email', models.CharField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, max_length=200, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('child_image', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=17, null=True)),
                ('parent_phone', models.CharField(blank=True, max_length=17, null=True)),
                ('removed', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('can_resend_activation', models.IntegerField()),
            ],
            options={
                'db_table': 'school_children',
                'managed': False,
            },
        ),
    ]
